// Generated by CoffeeScript 1.3.3
(function() {
  var $, convertToKmH, loaddata;

  $ = jQuery;

  $(document).ready(function() {
    return $("#data").change(function() {
      return loaddata(this);
    });
  });

  convertToKmH = function(ms) {
    var kmh;
    return kmh = ms * 60 * 60 / 1000;
  };

  loaddata = function(x) {
    var g, i, logEntries, max, min, min_max, speed, status_bar, xml, xmlDoc;
    xml = $.parseXML($(x).val());
    xmlDoc = $(xml);
    i = 0;
    speed = new Array;
    logEntries = xmlDoc.find("LogEntry").each(function() {
      return speed[i++] = convertToKmH(parseFloat($(this).find("Speed").text()));
    });
    min_max = Ico.series_min_max([speed]);
    min = min_max[0];
    max = min_max[1];
    status_bar = {
      x: 100,
      y: 8,
      attributes: {
        'font-size': '14',
        fill: '#642',
        'text-anchor': 'middle'
      }
    };
    return g = new Ico.LineGraph($('graph'), [speed], {
      min: min,
      max: max,
      font_size: 12,
      series_names: ['one'],
      value_labels: {
        add_padding: false
      },
      units: 'km/h',
      units_position: 100,
      x_padding_right: 15,
      colors: ['#228899'],
      mouseover_attributes: {
        stroke: 'green'
      },
      curve_amount: 3,
      mouse_pointer: true,
      status_bar: status_bar,
      grid: true,
      markers: false,
      marker_size: 5
    });
  };

}).call(this);
